// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderDetail _$OrderDetailFromJson(Map<String, dynamic> json) => OrderDetail(
      status: json['status'] as String?,
      payMethod: json['PayMethod'] as String?,
      subTotal: json['subTotal'].toString(),
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      joborderItemsId: json['joborderItemsId'] as int?,
      custPhone: json['custPhone'] as String?,
      walletAmount: (json['walletAmount'] as num?)?.toDouble(),
      orderNote: json['orderNote'] as String?,
      custBillingAdressId: json['custBillingAdressId'] as int?,
      custShippingAdressId: json['custShippingAdressId'] as int?,
      jobOrderId: json['jobOrderId'] as int?,
      joborderNumber: json['joborderNumber'] as int?,
      joborderDate: json['joborderDate'] as String?,
      orderId: json['orderId'] as int?,
      cartID: json['cartID'] as int?,
      custId: json['custId'] as int?,
      orderDate: json['orderDate'] as String?,
      orderAmount: (json['orderAmount'] as num?)?.toDouble(),
      jorderTax: (json['orderTax'] as num?)?.toDouble(),
      orderDiscount: (json['orderDiscount'] as num?)?.toDouble(),
      orderStatus: json['orderStatus'] as String?,
      orderDeliveryDate: json['orderDeliveryDate'] as String?,
      orderCancelledDate: json['orderCancelledDate'] as String?,
      orderReturnDate: json['orderReturnDate'] as String?,
      orderReturnStatus: json['orderReturnStatus'] as String?,
      returnOrderId: json['returnOrderId'] as int?,
      delDate: json['delDate'] as String?,
      orderDeliveryCharge: (json['orderDeliveryCharge'] as num?)?.toDouble(),
      orderNumber: json['orderNumber'] as String?,
      cpId: json['cpId'] as String?,
      couponDiscount: (json['couponDiscount'] as num?)?.toDouble(),
      orderWeight: json['orderWeight'] as String?,
      orderPincode: json['orderPincode'] as int?,
      OTP: json['OTP'] as String?,
      OTPExpiry: json['OTPExpiry'] as String?,
    );

Map<String, dynamic> _$OrderDetailToJson(OrderDetail instance) =>
    <String, dynamic>{
      'status': instance.status,
      'PayMethod': instance.payMethod,
      'subTotal': instance.subTotal,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'joborderItemsId': instance.joborderItemsId,
      'custPhone': instance.custPhone,
      'walletAmount': instance.walletAmount,
      'orderNote': instance.orderNote,
      'custBillingAdressId': instance.custBillingAdressId,
      'custShippingAdressId': instance.custShippingAdressId,
      'jobOrderId': instance.jobOrderId,
      'joborderNumber': instance.joborderNumber,
      'joborderDate': instance.joborderDate,
      'orderId': instance.orderId,
      'cartID': instance.cartID,
      'custId': instance.custId,
      'orderDate': instance.orderDate,
      'orderAmount': instance.orderAmount,
      'orderTax': instance.jorderTax,
      'orderDiscount': instance.orderDiscount,
      'orderStatus': instance.orderStatus,
      'orderDeliveryDate': instance.orderDeliveryDate,
      'orderCancelledDate': instance.orderCancelledDate,
      'orderReturnDate': instance.orderReturnDate,
      'orderReturnStatus': instance.orderReturnStatus,
      'returnOrderId': instance.returnOrderId,
      'delDate': instance.delDate,
      'orderDeliveryCharge': instance.orderDeliveryCharge,
      'orderNumber': instance.orderNumber,
      'cpId': instance.cpId,
      'couponDiscount': instance.couponDiscount,
      'orderWeight': instance.orderWeight,
      'orderPincode': instance.orderPincode,
      'OTP': instance.OTP,
      'OTPExpiry': instance.OTPExpiry,
    };
