// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_detail_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductDetailResponse _$ProductDetailResponseFromJson(
        Map<String, dynamic> json) =>
    ProductDetailResponse(
      catName: json['catName'] as String?,
      imageUrl: json['imageUrl'] as String?,
      parentId: json['parentId'] as int?,
      catId: json['catId'] as int?,
      prName: json['prName'] as String?,
      venderName: json['venderName'] as String?,
      IsAvailPincode: json['IsAvailPincode'] as bool?,
      IsCarted: json['IsCarted'] as bool?,
      IsReviewAvgrating: (json['IsReviewAvgrating'] as num?)?.toDouble(),
      IsReviewCount: json['IsReviewCount'] as int?,
      IsWishlisted: json['IsWishlisted'] as bool?,
      Reviewstatus: json['Reviewstatus'] as int?,
      actDate: json['actDate'] as String?,
      attributeSetId: json['attributeSetId'] as int?,
      availableFrom: json['availableFrom'] as String?,
      availableTo: json['availableTo'] as String?,
      avgRating: json['avgRating'] as int?,
      backOrders: json['backOrders'] as bool?,
      bvValue: json['bvValue'] as int?,
      soldQty: (json['soldQty'] as num?)?.toDouble(),
      catStatus: json['catStatus'] as bool?,
      catUrlKey: json['catUrlKey'] as String?,
      cessAmount: json['cessAmount'] as int?,
      comboProducts: json['comboProducts'] as String?,
      dealFrom: json['dealFrom'] as String?,
      dealTo: json['dealTo'] as String?,
      delDate: json['delDate'] as String?,
      description: json['description'] as String?,
      featuredImage: json['featuredImage'] as String?,
      maxQtyInOrders: (json['maxQtyInOrders'] as num?)?.toDouble(),
      metaDescription: json['metaDescription'] as String?,
      metaKeywords: json['metaKeywords'] as String?,
      metaTitle: json['metaTitle'] as String?,
      minOrderQty: json['minOrderQty'] as int?,
      minQtyInOrders: json['minQtyInOrders'] as int?,
      newDate: json['newDate'] as String?,
      pincodeSetId: json['pincodeSetId'] as int?,
      prDate: json['prDate'] as String?,
      prWeight: json['prWeight'] as int?,
      productId: json['productId'] as int?,
      productType: json['productType'] as String?,
      qoh: (json['qoh'] as num?)?.toDouble(),
      rank: json['rank'] as int?,
      reviewCount: json['reviewCount'] as String?,
      rol: (json['rol'] as num?)?.toDouble(),
      roq: (json['roq'] as num?)?.toDouble(),
      shortDescription: json['shortDescription'] as String?,
      sku: json['sku'] as String?,
      specialPrice: (json['specialPrice'] as num?)?.toDouble(),
      status: json['status'] as bool?,
      stockAvailability: json['stockAvailability'] as String?,
      suspendedDate: json['suspendedDate'] as String?,
      taxClassId: json['taxClassId'] as int?,
      unitPrice: (json['unitPrice'] as num?)?.toDouble(),
      urlKey: json['urlKey'] as String?,
      variationJson: json['variationJson'] as int?,
      venderDetails: json['venderDetails'] as String?,
      vendorUrlKey: json['vendorUrlKey'] as String?,
      qty: (json['qty'] as num?)?.toDouble(),
      vendorid: json['vendorid'] as int?,
    );

Map<String, dynamic> _$ProductDetailResponseToJson(
        ProductDetailResponse instance) =>
    <String, dynamic>{
      'venderName': instance.venderName,
      'catName': instance.catName,
      'catId': instance.catId,
      'prName': instance.prName,
      'parentId': instance.parentId,
      'imageUrl': instance.imageUrl,
      'venderDetails': instance.venderDetails,
      'vendorUrlKey': instance.vendorUrlKey,
      'variationJson': instance.variationJson,
      'catUrlKey': instance.catUrlKey,
      'IsWishlisted': instance.IsWishlisted,
      'catStatus': instance.catStatus,
      'IsCarted': instance.IsCarted,
      'IsAvailPincode': instance.IsAvailPincode,
      'IsReviewCount': instance.IsReviewCount,
      'Reviewstatus': instance.Reviewstatus,
      'IsReviewAvgrating': instance.IsReviewAvgrating,
      'productId': instance.productId,
      'vendorid': instance.vendorid,
      'prDate': instance.prDate,
      'actDate': instance.actDate,
      'sku': instance.sku,
      'unitPrice': instance.unitPrice,
      'description': instance.description,
      'shortDescription': instance.shortDescription,
      'urlKey': instance.urlKey,
      'metaTitle': instance.metaTitle,
      'metaKeywords': instance.metaKeywords,
      'metaDescription': instance.metaDescription,
      'status': instance.status,
      'qoh': instance.qoh,
      'rank': instance.rank,
      'availableFrom': instance.availableFrom,
      'availableTo': instance.availableTo,
      'suspendedDate': instance.suspendedDate,
      'newDate': instance.newDate,
      'delDate': instance.delDate,
      'maxQtyInOrders': instance.maxQtyInOrders,
      'soldQty': instance.soldQty,
      'stockAvailability': instance.stockAvailability,
      'backOrders': instance.backOrders,
      'rol': instance.rol,
      'roq': instance.roq,
      'specialPrice': instance.specialPrice,
      'attributeSetId': instance.attributeSetId,
      'pincodeSetId': instance.pincodeSetId,
      'prWeight': instance.prWeight,
      'taxClassId': instance.taxClassId,
      'cessAmount': instance.cessAmount,
      'dealFrom': instance.dealFrom,
      'dealTo': instance.dealTo,
      'featuredImage': instance.featuredImage,
      'avgRating': instance.avgRating,
      'reviewCount': instance.reviewCount,
      'minQtyInOrders': instance.minQtyInOrders,
      'comboProducts': instance.comboProducts,
      'productType': instance.productType,
      'minOrderQty': instance.minOrderQty,
      'bvValue': instance.bvValue,
      'qty': instance.qty,
    };
